### ISSUE TITLE
CORs is not enabled in the back-end

### ISSUE THREAD

**Issue by jnahas55** [iot-uca/back-end#105]
When performing a POST request to add a data-stream, the response is 404 and the message indicates that the CORs preflight request is not being accepted by the server.

![image](https://user-images.githubusercontent.com/18634505/42067518-fa7b3e1a-7b1c-11e8-8c09-18be1883bffd.png)

**Comment by fortizpenaloza** [comment]
@jnahas55 try adding a data stream using the latest version.

**Comment by jnahas55** [comment]
User is able to add _data-stream_s now... However for _actions_ **OPTION** method does not seem to be defined. Please see image attached.

![image](https://user-images.githubusercontent.com/18634505/42194898-98dc6b38-7e4c-11e8-963d-763e66f7ac0f.png)

**Comment by fortizpenaloza** [comment]
@jnahas55 I pulled your latest commit and I wasn't able to perform a POST to /actions.

Request to http://192.168.99.100:8090/actions timed out.

It would be great if you extract the API base URL "http://192.168.99.100:8090" to a project variable to make it easier to test the integration.

**Comment by jnahas55** [comment]
@fortizpenaloza the variable has been added under the name _backendEndPoint_. Let me know how it goes...
