### ISSUE TITLE
Querying commands according to priority not working as expected

### ISSUE THREAD

**Issue by jnahas55** [iot-uca/back-end#185]
When you register commands with different priorities and then query them for that criteria, Cosmos answer is not the expected one:

Steps to reproduce:

1) Register commands as the screenshot shows

![commands_register_order](https://user-images.githubusercontent.com/18634505/53755121-82ad7b00-3e94-11e9-831a-c57677613b14.png)

2) Query them via http://localhost:8090/commands?order=priority

3) Got response:

`[{"command":"Command7","priority":"77","links":{"self":"http://localhost:8090/commands/571e341f-aa3f-0d00-bcfd-699b0bb0162f"}},{"command":"Command1","priority":"22","links":{"self":"http://localhost:8090/commands/4a5f071c-aa3f-0d00-bcfb-571e0bb0162f"}},{"command":"Command2","priority":"2","links":{"self":"http://localhost:8090/commands/1b7a8b2e-aa3f-0d00-bcfe-42990bb0162f"}},{"command":"Command3","priority":"11","links":{"self":"http://localhost:8090/commands/63ced01c-aa3f-0d00-bcfc-910b0bb0162f"}},{"command":"Command6","priority":"100","links":{"self":"http://localhost:8090/commands/8b81df45-aa3f-0d00-bcff-77000bb0162f"}}]`

Expected response order:  100, 77, 22, 11, 2

Tested on Cosmos' latest available version [March 4, 10:16 AM, associated with commit https://www.github.com/iot-uca/back-end/tree/7a00120255221ed71d92e9ef7f8e8b8c4eba6889].

**Comment by fortizpenaloza** [comment]
@jnahas55 I test it and it's working fine. Now you can't register priorities as strings.

**Comment by jnahas55** [comment]
Retested and working as expected. Minor comment: When the user send the priority as a String, Cosmos container announces 

_[2019-05-09T02:59:02.558333+00:00] [ERROR] Dumping Stack Due to Unexpected Error: A command's priority must be an integer... [OK]_
