### ISSUE TITLE
User can define a Trigger without a given name

### ISSUE THREAD

**Issue by jnahas55** [iot-uca/back-end#188]
_Headers_
Host: localhost:8090
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain, */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:7080/triggers
Content-Type: application/json;charset=utf-8
Content-Length: 118
Origin: http://localhost:7080
Connection: keep-alive

_Body_
{"name":"","action":"Action1","policy":{"type":"data_point_registration","data_stream":"DataStream1"},"conditions":[]}

Tested against latest Cosmos Docker image available (Commit Source: 9096a8f).

![trigger_empty_name](https://user-images.githubusercontent.com/18634505/56781315-2e01ee80-67b9-11e9-8642-a0b3dcfd2835.png)

![trigger_empty_name_2](https://user-images.githubusercontent.com/18634505/56781495-bf716080-67b9-11e9-9b02-f28f987c26cd.png)

**Comment by fortizpenaloza** [comment]
Fixed by #189

**Comment by jnahas55** [comment]
Retested with latest Docker image and working as expected.
